### ISSUE TITLE
queue controls break when queue contains duplicate songs

### ISSUE THREAD

**Issue by connorworley** [robertlai/karafriends#34]
<img width="791" alt="Screen Shot 2021-05-13 at 5 32 39 PM" src="https://user-images.githubusercontent.com/1512426/118203606-45988800-b411-11eb-8d8e-78babbbf7c30.png">

**Comment by robertlai** [comment]
i swear i made it a string

**Comment by robertlai** [comment]
or is id a special name? what is this
